KAFKA_CONNECTOR_TOPIC_NAME="stations"
WEATHER_TOPIC_NAME="org.chicago.cta.weather.v1"
STATION_TOPIC_PREFIX="org.chicago.cta.station.arrivals"
TURNSTILE_SUMMARY_TOPIC="TURNSTILE_SUMMARY"
TURNSTILE_TOPIC_NAME="org.chicago.cta.turnstile"
TRNAFORMED_STATION_TOPIC_NAME="org.chicago.cta.stations.table.v1"